services:
  # Service Application Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage/logs:/var/www/storage/logs
    networks:
      - laravel
    depends_on:
      - mysql
      - redis

  # Service Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel
    depends_on:
      - app

  # Service MySQL
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: eclat_back
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: password123
      MYSQL_USER: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel

  # Service Redis
  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
     - "6380:6379"
    networks:
      - laravel

  # Service Node.js
  node:
    image: node:20-alpine
    container_name: laravel-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    command: sh -c "if [ -f package.json ]; then npm install && npm run dev; else tail -f /dev/null; fi"
    ports:
      - "5173:5173"
    depends_on:
      - app

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
    driver: local